// flow-typed signature: 3c59a2ba69c5a44bab0a04d6bdd36c90
// flow-typed version: <<STUB>>/react-firebaseui_v^1.1.9/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-firebaseui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-firebaseui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-firebaseui/FirebaseAuth' {
  declare module.exports: any;
}

declare module 'react-firebaseui/StyledFirebaseAuth' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-firebaseui/FirebaseAuth.js' {
  declare module.exports: $Exports<'react-firebaseui/FirebaseAuth'>;
}
declare module 'react-firebaseui/index' {
  declare module.exports: $Exports<'react-firebaseui'>;
}
declare module 'react-firebaseui/index.js' {
  declare module.exports: $Exports<'react-firebaseui'>;
}
declare module 'react-firebaseui/StyledFirebaseAuth.js' {
  declare module.exports: $Exports<'react-firebaseui/StyledFirebaseAuth'>;
}
