version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.1
executors:
  default:
    docker:
      - image: cimg/node:18.12.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

  save_cache_cmd:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  client_install_cmd:
    steps:
      - run:
          name: Install Client Dependencies
          working_directory: ~/project
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

  server_install_cmd:
    steps:
      - run:
          name: Install Server Dependencies
          working_directory: ~/project/server
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

  cdk_install_cmd:
    steps:
      - node/install-packages:
          app-dir: ~/project/cdk

  test_cmd:
    steps:
      - run:
          command: yarn test

  setup_cmd:
    steps:
      - checkout
      - aws-cli/install
      - restore_cache_cmd
      - cdk_install_cmd
      - server_install_cmd
      - client_install_cmd
      - save_cache_cmd

  test_client:
    steps:
      - run:
          command: yarn test
          working_directory: ~/project/client

  test_server:
    steps:
      - run:
          command: yarn test:ci
          working_directory: ~/project/server

  deploy_cmd:
    steps:
      - run:
          command: ./scripts/build.sh
          working_directory: ~/project/server
      - run:
          command: yarn build
          working_directory: ~/project
      - run:
          command: npm run build
          working_directory: ~/project/cdk
      - run:
          command: npm run deploy
          working_directory: ~/project/cdk

jobs:
  test:
    executor: default
    steps:
      - setup_cmd
      - test_server
      - test_cmd
  test-and-deploy:
    executor: default
    steps:
      - setup_cmd
      - test_server
      - test_cmd
      - deploy_cmd

workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - test-and-deploy:
          context:
            - scottdb
          filters:
            branches:
              only: master
