version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
executors:
  default:
    docker:
      - image: cimg/node:12.18

jobs:
  client-test-deploy:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - aws-cli/install
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: yarn test
      - run:
          command: yarn deploy

workflows:
  test-and-deploy-all:
    jobs:
      - client-test-deploy:
          context:
            - scottdb
          filters:
            branches:
              only: master
